version: '3'

services:

  backdraft:
    build: .
    env_file:
      - config/django/django_env
    volumes:
      - .:/opt/services/backdraft
      - static_volume:/opt/services/backdraft/static
      - media_volume:/opt/services/backdraft/media
      - jenkins_data:/var/jenkins_home
    networks:
      - nginx_network
      - database1_network
    depends_on:
      - database1

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/backdraft/static
      - media_volume:/opt/services/backdraft/media
    depends_on:
      - backdraft
    networks:
      - nginx_network

  database1:
    image: postgres:10
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
        - "8080:8080"
        - "50000:50000"
    volumes:
        - jenkins_data:/var/jenkins_home

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  database1_volume:
  static_volume:
  media_volume:
  jenkins_data:
